version: "3.7"

services:

  xnat-smtp:
    container_name: xnat-smtp
    image: freinet/postfix-relay
    networks: [xnat-services]
    environment:
      MAILNAME: ${REMOTE_SMTP_DOMAIN}
      TZ: ${REMOTE_SMTP_LOCAL_TZ}
      RELAYHOST: ${REMOTE_SMTP_HOST}:${REMOTE_SMTP_PORT}
      RELAYHOST_AUTH: ${REMOTE_SMTP_ENABLE_AUTH}
      RELAYHOST_PASSWORDMAP: ${REMOTE_SMTP_HOST}:${REMOTE_SMTP_USERNAME}:${REMOTE_SMTP_PASSWORD}

networks:
  xnat-services:
    name: xnat-services
    driver: bridge
